// ============================================================
// RED ACADEMY — MOCK DATA FOR DEVELOPMENT
// ============================================================

import {
  Batch,
  Trainee,
  DailyAttendance,
  Attendance10Day,
  Assessment,
  CompanyEnum,
} from "@/types";

// Sample batches
export const mockBatches: Batch[] = [
  {
    id: "batch-31",
    batchName: "Batch 31",
    status: "Active",
    dateRange: {
      start: new Date("2026-01-20"),
      end: new Date("2026-02-10"),
    },
    trainees: [],
    attendanceLogs: [],
    attendance10DayLogs: [],
    assessments: [],
    absentTotal10Day: 12,
    presentTotal10Day: 88,
    lateTotal10Day: 15,
    avgCompletion10Day: 78,
  },
  {
    id: "batch-30",
    batchName: "Batch 30",
    status: "Completed",
    dateRange: {
      start: new Date("2026-01-05"),
      end: new Date("2026-01-19"),
    },
    trainees: [],
    attendanceLogs: [],
    attendance10DayLogs: [],
    assessments: [],
    absentTotal10Day: 8,
    presentTotal10Day: 92,
    lateTotal10Day: 10,
    avgCompletion10Day: 95,
  },
  {
    id: "batch-32",
    batchName: "Batch 32",
    status: "Planning",
    dateRange: {
      start: new Date("2026-02-15"),
      end: new Date("2026-02-28"),
    },
    trainees: [],
    attendanceLogs: [],
    attendance10DayLogs: [],
    assessments: [],
    absentTotal10Day: 0,
    presentTotal10Day: 0,
    lateTotal10Day: 0,
    avgCompletion10Day: 0,
  },
];

// Sample trainees
export const mockTrainees: Trainee[] = [
  {
    id: "trainee-1",
    traineeName: "Karim Mahmoud",
    company: "RED",
    batchId: "batch-31",
    attendanceLogs: [],
    attendance10Day: [],
    presentDaily: 8,
    absentDaily: 1,
    latesDaily: 2,
    present10Day: 8,
    absent10Day: 2,
    late10Day: 1,
    latestCompletion10Day: 90,
  },
  {
    id: "trainee-2",
    traineeName: "Rowan Alaa",
    company: "Impact",
    batchId: "batch-31",
    attendanceLogs: [],
    attendance10Day: [],
    presentDaily: 9,
    absentDaily: 0,
    latesDaily: 1,
    present10Day: 9,
    absent10Day: 1,
    late10Day: 0,
    latestCompletion10Day: 100,
  },
  {
    id: "trainee-3",
    traineeName: "Ahmed Hassan",
    company: "Casablanca",
    batchId: "batch-31",
    attendanceLogs: [],
    attendance10Day: [],
    presentDaily: 7,
    absentDaily: 2,
    latesDaily: 3,
    present10Day: 7,
    absent10Day: 3,
    late10Day: 2,
    latestCompletion10Day: 70,
  },
  {
    id: "trainee-4",
    traineeName: "Sara Mohamed",
    company: "Petra",
    batchId: "batch-31",
    attendanceLogs: [],
    attendance10Day: [],
    presentDaily: 6,
    absentDaily: 3,
    latesDaily: 1,
    present10Day: 6,
    absent10Day: 4,
    late10Day: 1,
    latestCompletion10Day: 60,
  },
  {
    id: "trainee-5",
    traineeName: "Omar Khaled",
    company: "Housology",
    batchId: "batch-31",
    attendanceLogs: [],
    attendance10Day: [],
    presentDaily: 10,
    absentDaily: 0,
    latesDaily: 0,
    present10Day: 10,
    absent10Day: 0,
    late10Day: 0,
    latestCompletion10Day: 100,
  },
];

// Sample daily attendance
export const mockDailyAttendance: DailyAttendance[] = [
  {
    id: "att-1",
    entryId: "2026-02-03 - Karim Mahmoud",
    date: new Date("2026-02-03"),
    arrivalTime: new Date("2026-02-03T10:20:00"),
    departureTime: new Date("2026-02-03T18:00:00"),
    status: "Present",
    isLate: false,
    traineeId: "trainee-1",
    batchId: "batch-31",
    minutesLate: 0,
    wasLate: false,
  },
  {
    id: "att-2",
    entryId: "2026-02-03 - Rowan Alaa",
    date: new Date("2026-02-03"),
    arrivalTime: new Date("2026-02-03T10:30:00"),
    departureTime: new Date("2026-02-03T18:00:00"),
    status: "Present",
    isLate: false,
    traineeId: "trainee-2",
    batchId: "batch-31",
    minutesLate: 0,
    wasLate: false,
  },
  {
    id: "att-3",
    entryId: "2026-02-03 - Ahmed Hassan",
    date: new Date("2026-02-03"),
    arrivalTime: new Date("2026-02-03T11:45:00"),
    departureTime: new Date("2026-02-03T17:30:00"),
    status: "Present",
    isLate: true,
    traineeId: "trainee-3",
    batchId: "batch-31",
    minutesLate: 45,
    wasLate: true,
  },
  {
    id: "att-4",
    entryId: "2026-02-03 - Sara Mohamed",
    date: new Date("2026-02-03"),
    arrivalTime: null,
    departureTime: null,
    status: "Absent",
    isLate: false,
    traineeId: "trainee-4",
    batchId: "batch-31",
    minutesLate: 0,
    wasLate: false,
  },
  {
    id: "att-5",
    entryId: "2026-02-03 - Omar Khaled",
    date: new Date("2026-02-03"),
    arrivalTime: new Date("2026-02-03T09:00:00"),
    departureTime: new Date("2026-02-03T14:00:00"),
    status: "Tour Day",
    isLate: false,
    traineeId: "trainee-5",
    batchId: "batch-31",
    minutesLate: 0,
    wasLate: false,
  },
];

// Sample 10-day attendance
export const mock10DayAttendance: Attendance10Day[] = [
  {
    id: "10day-1",
    record: "Karim Mahmoud - Batch 31 (Jan 20–Jan 30)",
    periodStart: new Date("2026-01-20"),
    periodEnd: new Date("2026-01-30"),
    day1: true,
    day2: true,
    day3: true,
    day4: true,
    day5: true,
    day6: true,
    day7: true,
    day8: true,
    day9: true,
    day10: false,
    completionPercent: 90,
    checklistStatus: "In Progress",
    attendanceAIReport: "Strong attendance pattern with consistent presence.",
    traineeId: "trainee-1",
    batchId: "batch-31",
    dailyEntries: [],
    assessments: [],
    presentCount: 9,
    absentCount: 1,
    lateCount: 1,
  },
  {
    id: "10day-2",
    record: "Rowan Alaa - Batch 31 (Jan 20–Jan 30)",
    periodStart: new Date("2026-01-20"),
    periodEnd: new Date("2026-01-30"),
    day1: true,
    day2: true,
    day3: true,
    day4: true,
    day5: true,
    day6: true,
    day7: true,
    day8: true,
    day9: true,
    day10: true,
    completionPercent: 100,
    checklistStatus: "Complete",
    attendanceAIReport: "Perfect attendance! Exemplary commitment shown.",
    traineeId: "trainee-2",
    batchId: "batch-31",
    dailyEntries: [],
    assessments: [],
    presentCount: 10,
    absentCount: 0,
    lateCount: 0,
  },
];

// Sample assessments
export const mockAssessments: Assessment[] = [
  {
    id: "assess-1",
    assessmentTitle: "Final Batch 31",
    mapping: 5,
    productKnowledge: 5,
    presentability: 5,
    softSkills: 4.5,
    attendance: 9,
    absence: 1,
    assessmentOutcome: "Aced",
    instructorComment:
      "Exceptional technical knowledge, high mapping skills, very committed candidate.",
    assessmentAIReport:
      "Karim demonstrates outstanding proficiency across all assessment areas.",
    company: "RED",
    traineeId: "trainee-1",
    batchId: "batch-31",
    techScorePercent: 100,
    softScorePercent: 95,
    overallPercent: 97.5,
  },
  {
    id: "assess-2",
    assessmentTitle: "Final Batch 31",
    mapping: 4,
    productKnowledge: 4.5,
    presentability: 5,
    softSkills: 5,
    attendance: 10,
    absence: 0,
    assessmentOutcome: "Excellent",
    instructorComment: "Great soft skills and excellent presentation ability.",
    assessmentAIReport:
      "Rowan shows exceptional interpersonal skills with strong technical foundation.",
    company: "Impact",
    traineeId: "trainee-2",
    batchId: "batch-31",
    techScorePercent: 85,
    softScorePercent: 100,
    overallPercent: 92.5,
  },
];

// Dashboard statistics
export const mockDashboardStats = {
  activeBatches: 3,
  planningBatches: 2,
  completedBatches: 28,
  totalTrainees: 512,
  todayPresent: 45,
  todayAbsent: 8,
  todayLate: 12,
  todayOnTour: 5,
  attendancePercent: 73,
  weeklyTrend: [
    { day: "Mon", value: 68 },
    { day: "Tue", value: 71 },
    { day: "Wed", value: 76 },
    { day: "Thu", value: 73 },
    { day: "Fri", value: 79 },
    { day: "Sat", value: 75 },
    { day: "Sun", value: 73 },
  ],
  outcomeDistribution: [
    { name: "Aced", value: 67 },
    { name: "Excellent", value: 18 },
    { name: "Good", value: 10 },
    { name: "Needs Improvement", value: 5 },
  ],
  topCompanies: [
    { name: "RED", trainees: 156 },
    { name: "Impact", trainees: 89 },
    { name: "Casablanca", trainees: 67 },
    { name: "Petra", trainees: 54 },
    { name: "Housology", trainees: 32 },
  ],
};
